apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: backend
type: Opaque
data:
  username: YWRtaW4= # admin
  password: YWRtaW5wYXNz # adminpass

# mysql -u admin -p
# SHOW DATABASES;
# USE mydatabase;
# SHOW TABLES;
# SELECT * FROM users;

