name: Deploy to EKS

on:
  workflow_dispatch:  # Allows manual triggers of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Replace with your AWS region

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.27.2  # Replace with the kubectl version you need

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0  # Replace with the Helm version you need

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region us-east-1 --name your-eks-cluster-name

    - name: Deploy Helm chart
      run: |
        helm upgrade --install backend-deploy ./backend-deploy/backend \
          --namespace your-namespace --create-namespace \
          --values ./backend-deploy/backend/values.yaml

